/**
 * SOUL.md 生成器
 * 根据用户资料生成标准化的 SOUL.md 文件
 */

export function generateSoulMd(profile: Record<string, any>): string {
  const date = new Date().toISOString().split('T')[0];
  
  let md = `# SOUL.md - ${profile.name || 'Anonymous'}

> Generated by ME Tool v1.0
> Last Updated: ${date}

---

## 🎯 Identity (身份识别)

| Field | Value |
|-------|-------|
| **Name** | ${profile.name || '-'} |
| **Title** | ${profile.title || '-'} |
| **Location** | ${profile.location || '-'} |
| **Avatar** | ${profile.avatar || '-'} |

---

## 📝 Bio (个人简介)

${profile.about || 'No bio provided.'}

---

## 🔗 Connect (社交链接)

`;

  if (profile.social && profile.social.length > 0) {
    profile.social.forEach(link => {
      md += `- **${link.platform}**: ${link.url}\n`;
    });
  } else {
    md += '_No social links provided._\n';
  }

  md += `
---

## 💡 Skills (技能专长)

`;

  if (profile.skills && profile.skills.length > 0) {
    profile.skills.forEach(skill => {
      md += `### ${skill.name}\n`;
      md += `- **Level**: ${skill.level}\n`;
      md += `- **Technologies**: ${skill.technologies?.map(t => typeof t === 'object' ? t.name : t).join(', ') || '-'}\n\n`;
    });
  } else {
    md += '_No skills provided._\n';
  }

  md += `
---

## 🚀 Projects (项目作品)

`;

  if (profile.projects && profile.projects.length > 0) {
    profile.projects.forEach(project => {
      md += `### ${project.title}\n`;
      md += `${project.description}\n\n`;
      md += `- **Tech Stack**: ${project.technologies?.join(', ') || '-'}\n`;
      if (project.github) md += `- **GitHub**: ${project.github}\n`;
      if (project.live) md += `- **Live Demo**: ${project.live}\n`;
      
      if (project.highlights && project.highlights.length > 0) {
        md += `- **Highlights**:\n`;
        project.highlights.forEach(h => {
          md += `  - ${h}\n`;
        });
      }
      md += '\n';
    });
  } else {
    md += '_No projects provided._\n';
  }

  md += `
---

## 💼 Experience (工作经历)

`;

  if (profile.experience && profile.experience.length > 0) {
    profile.experience.forEach(exp => {
      md += `### ${exp.title} @ ${exp.company}\n`;
      md += `- **Period**: ${exp.period}\n`;
      md += `- **Description**: ${exp.description}\n`;
      
      if (exp.achievements && exp.achievements.length > 0) {
        md += `- **Achievements**:\n`;
        exp.achievements.forEach(a => {
          md += `  - ${a}\n`;
        });
      }
      md += '\n';
    });
  } else {
    md += '_No experience provided._\n';
  }

  md += `
---

## 🦞 Lobster Communities (龙虾社区)

`;

  if (profile.lobsterCommunities && profile.lobsterCommunities.length > 0) {
    profile.lobsterCommunities.forEach(community => {
      md += `### ${community.platform}\n`;
      md += `- **ID**: ${community.id}\n`;
      if (community.tags && community.tags.length > 0) {
        md += `- **Preset Tags**: ${community.tags.join(', ')}\n`;
      }
      md += '\n';
    });
  } else {
    md += '_No lobster community connections configured._\n';
  }

  md += `
---

## 📊 Meta

| Property | Value |
|----------|-------|
| **Generator** | ME Tool |
| **Version** | 1.0.0 |
| **Format** | SOUL.md v1 |
| **Generated** | ${date} |

---

*This SOUL.md file was generated by [ME Tool](https://github.com/yourusername/me) - Create your own at the link!*
`;

  return md;
}

export function downloadSoulMd(profile: Record<string, any>, filename: string = 'SOUL.md'): void {
  const content = generateSoulMd(profile);
  const blob = new Blob([content], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
