import { describe, it, expect } from 'vitest';
import { exportToYAML } from './yaml';

describe('yaml exporter', () => {
  const sampleProfile = {
    name: 'Test User',
    title: 'Engineer',
    location: 'Test City',
    social: [{ platform: 'GitHub', url: 'https://github.com/test' }],
    skills: [{ name: 'JavaScript', level: 'Advanced' }],
  };

  it('should produce a header comment with tool info and date', () => {
    const result = exportToYAML(sampleProfile);
    expect(result).toContain('# Profile Export');
    expect(result).toContain('# Generated by ME Tool v1.0.0');
    expect(result).toContain('# Date:');
  });

  it('should contain profile name as a top-level key', () => {
    const result = exportToYAML(sampleProfile);
    expect(result).toContain('name: Test User');
  });

  it('should contain profile title', () => {
    const result = exportToYAML(sampleProfile);
    expect(result).toContain('title: Engineer');
  });

  it('should handle nested objects', () => {
    const profile = {
      name: 'Test',
      address: { city: 'Test City', country: 'Testland' },
    };
    const result = exportToYAML(profile);
    expect(result).toContain('address:');
    expect(result).toContain('city: Test City');
    expect(result).toContain('country: Testland');
  });

  it('should handle arrays of objects', () => {
    const result = exportToYAML(sampleProfile);
    expect(result).toContain('social:');
    expect(result).toContain('- ');
    expect(result).toContain('platform: GitHub');
  });

  it('should handle arrays of primitives', () => {
    const profile = {
      tags: ['developer', 'engineer', 'test'],
    };
    const result = exportToYAML(profile);
    expect(result).toContain('tags:');
    expect(result).toContain('- developer');
    expect(result).toContain('- engineer');
    expect(result).toContain('- test');
  });

  it('should handle empty arrays', () => {
    const profile = { items: [] };
    const result = exportToYAML(profile);
    expect(result).toContain('items: []');
  });

  it('should handle null and undefined values', () => {
    const profile = { a: null, b: undefined };
    const result = exportToYAML(profile);
    expect(result).toContain('a: null');
    expect(result).toContain('b: null');
  });

  it('should handle multiline strings with pipe notation', () => {
    const profile = { bio: 'Line one\nLine two\nLine three' };
    const result = exportToYAML(profile);
    expect(result).toContain('bio: |');
    expect(result).toContain('Line one');
    expect(result).toContain('Line two');
  });

  it('should handle numeric values', () => {
    const profile = { age: 30, score: 99.5 };
    const result = exportToYAML(profile);
    expect(result).toContain('age: 30');
    expect(result).toContain('score: 99.5');
  });

  it('should handle empty profile object', () => {
    const result = exportToYAML({});
    expect(result).toContain('# Profile Export');
    // Just the header, no keys
    const body = result.split('\n\n')[1];
    expect(body?.trim()).toBe('');
  });
});
