/**
 * YAML 导出器
 * 简单实现，不依赖外部库
 */

function stringifyYaml(obj, indent = 0) {
  const spaces = '  '.repeat(indent);
  let yaml = '';
  
  for (const [key, value] of Object.entries(obj)) {
    if (value === null || value === undefined) {
      yaml += `${spaces}${key}: null\n`;
    } else if (typeof value === 'object' && !Array.isArray(value)) {
      yaml += `${spaces}${key}:\n`;
      yaml += stringifyYaml(value, indent + 1);
    } else if (Array.isArray(value)) {
      if (value.length === 0) {
        yaml += `${spaces}${key}: []\n`;
      } else if (typeof value[0] === 'object') {
        yaml += `${spaces}${key}:\n`;
        value.forEach(item => {
          yaml += `${spaces}- \n`;
          yaml += stringifyYaml(item, indent + 1).split('\n')
            .filter(line => line.trim())
            .map(line => spaces + '  ' + line.trim())
            .join('\n') + '\n';
        });
      } else {
        yaml += `${spaces}${key}:\n`;
        value.forEach(item => {
          yaml += `${spaces}- ${item}\n`;
        });
      }
    } else if (typeof value === 'string') {
      // 处理多行字符串
      if (value.includes('\n')) {
        yaml += `${spaces}${key}: |\n`;
        value.split('\n').forEach(line => {
          yaml += `${spaces}  ${line}\n`;
        });
      } else {
        yaml += `${spaces}${key}: ${value}\n`;
      }
    } else {
      yaml += `${spaces}${key}: ${value}\n`;
    }
  }
  
  return yaml;
}

export function exportToYaml(profile) {
  const header = `# Profile Export\n# Generated by ME Tool v1.0.0\n# Date: ${new Date().toISOString()}\n\n`;
  return header + stringifyYaml(profile);
}

export function downloadYaml(profile, filename = 'profile.yaml') {
  const content = exportToYaml(profile);
  const blob = new Blob([content], { type: 'text/yaml' });
  const url = URL.createObjectURL(blob);
  
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
